controllers/ippool_controller.go
controllers/ippool_controller_test.go
go.mod
go.sum
ipam/ippool_manager.go

When the cluster is not found, it was attempting to set an owner reference with an empty name. This also updates the restrictions on the events triggering the reconciliation from IPClaims and IPAddress to catch deletion events

🐛 Fix bug when cluster is not found

---

.gitignore
tilt-provider.json

This is for metal3-io/cluster-api-provider-metal3#132

🏃 Add Tilt provider file for integration with CAPM3 Tilt setup

---

Dockerfile
Makefile
go.mod
hack/Dockerfile.unit
hack/codegen.sh
hack/ensure-go.sh
hack/gofmt.sh
hack/govet.sh
hack/tools/go.mod

In order to avoid differences in go version across all repositories, this PR updates go to the latest in hack scripts. The motivation behind this is from [project-infra/pull/124](https://github.com/metal3-io/project-infra/pull/124).

🏃 Update golang to latest to match version across all repos

---

docs/api.md

Updates api.md with missing spec field and it's definition.

📖 Fix missing field in api documentation

---

api/v1alpha1/ipaddress_types.go
api/v1alpha1/ipclaim_types.go
api/v1alpha1/ippool_types.go
config/crd/bases/ipam.metal3.io_ipaddresses.yaml
config/crd/bases/ipam.metal3.io_ipclaims.yaml
config/crd/bases/ipam.metal3.io_ippools.yaml

This is used to avoid naming conflicts with k8s resources' names.

🏃Rename shortNames with prefix 'm3' or 'metal3'

---

Dockerfile
Makefile
go.mod
hack/Dockerfile.unit
hack/codegen.sh
hack/ensure-go.sh
hack/gofmt.sh
hack/govet.sh
hack/tools/go.mod

Bump the Golang version to [1.16](https://blog.golang.org/go1.16)

🏃 Bump the Golang version to 1.16

---

api/v1alpha1/ippool_webhook.go
api/v1alpha1/ippool_webhook_test.go
api/v1alpha1/utils.go
api/v1alpha1/utils_test.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go

In case of pre-allocated addresses, the claims were not given the
proper prefix, gateway and dns server overrides. In addition to
fixing this, some validations on the pool updates are added to
verify that no addresses would be out of bonds.

🐛 Fix issue with pre-allocated addresses

---

config/manager/manager_auth_proxy_patch.yaml

Taking in changes as CAPI release-0.3 https://github.com/kubernetes-sigs/cluster-api/pull/4639

:sparkles: Uplift kube-rbac-proxy to v0.8.0

---

examples/generate.sh
examples/ippool/ippool.yaml

Fixes examples generation after CAPI uplift to v1a4.
Makes sure to run:
**- make deploy**
**- make deploy-examples**
**- make delete-examples**
Makefile targets successfully.

🐛 Fix examples generation

---

README.md

This updates root README file regarding IPAM compatibility with CAPI notes by adding extra column `IPAM Release` and specifying corresponding releases.

Update IPAM compatibility with CAPI in notes

---

api/v1alpha1/ipaddress_webhook.go
api/v1alpha1/ipclaim_webhook.go
api/v1alpha1/ippool_webhook.go
config/webhook/manifests.yaml

Webhook registration should accept both v1 and v1beta1 admissions
Admission Review was previously set to only accept v1beta1 objects given
that Controller Runtime didn't support v1 (even though the two revisions
are effectively the same). This change adds support for both within our
manifests.
equivalent of [kubernetes-sigs/cluster-api#4942](https://github.com/kubernetes-sigs/cluster-api/pull/4942)

🐛 Webhook reg should accept both v1 and v1beta1 admissions

---

main.go

Currently the readiness of our controller deployments does not include the webhook server. I.e., the deployment is already ready even when the webhooks are not up.
The current PR will help that the wait for readiness will also include the webhook server. This is crucial because otherwise there's a chance that clusterctl immediately fails when we try to deploy resources.
Follows: kubernetes-sigs/cluster-api#4989

✨ Add webhook readiness and health check

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
VERSIONING.md
hack/tools/release/notes.go

This PR changes the emoji used for the "Other" PR category to make it more inclusive
Aligns with CAPM3 emojis. Borrowed from [CAPM3#129](https://github.com/metal3-io/cluster-api-provider-metal3/pull/129)

🌱 Opt for a more inclusive Other PR category

---

api/v1alpha1/ipaddress_types.go
api/v1alpha1/ipclaim_types.go
api/v1alpha1/ippool_types.go
config/crd/bases/ipam.metal3.io_ipaddresses.yaml
config/crd/bases/ipam.metal3.io_ipclaims.yaml
config/crd/bases/ipam.metal3.io_ippools.yaml

This adds the AGE column to all our CRDs to make the printed output consistent with the built in K8s resources.
Keeping things consistent with CAPI# https://github.com/kubernetes-sigs/cluster-api/pull/5180

✨ Add AGE column to IPAM CRDs

---

api/v1alpha1/ipaddress_webhook.go
api/v1alpha1/ipclaim_webhook.go
api/v1alpha1/ippool_webhook.go
config/webhook/manifests.yaml

This PR updates leftover Provider API versions in webhooks from v1a4 to v1a5.

🐛 Fix API version in IPAM webhooks

---

CONTRIBUTING.md
Makefile
VERSIONING.md
config/default/manager_image_patch.yaml
docs/releasing.md
examples/generate.sh

Since we are changing main as the default branch, we also refer main branch instead of master .

⚠️  Add main branch reference

---

config/crd/kustomization.yaml

It is needed to conform with the CAPI CRD labeling
Related documentation can be found here:
https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#apply-the-contract-version-label-clusterx-k8sioversion-version1_version2_version3-to-your-crds
This update was also done to CAPM3, the current CAPM3 CRD labeling configuration can be found here:
https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/config/crd/kustomization.yaml

:sparkles: Update the contract labels for IPAM CRDS

---

hack/unit.sh

Use `docker.io/golang:1.16`  container image for unit.sh script.
We don't necessarily need to create & use `quay.io/metal3-io/capm3-unit`
image, because the only thing this image has is kustomize and
kubebuilder installed via below RUN, which is redundant as those
binaries will be installed during `unit` Makefile target ( as part of
`setup_envs`). At the end, we currently install kubebuilder and
kustomize twice. 
```
RUN ./install_kustomize.sh && \
./install_kubebuilder.sh
```
There will be a follow PR to this, which will remove the
Dockerfile, and update the project-infra respectively to migrate
fully to golang images.

🌱 Use golang image as base for unit test containers

---

hack/gofmt.sh
hack/govet.sh
hack/unit.sh

Replaces unrelated capm3 mentions with the proper path in the scripts under the hack folder

🐛Fix unrelated capm3 mentions under hack folder scripts

---

hack/gofmt.sh
hack/govet.sh
hack/unit.sh

Backport of https://github.com/metal3-io/ip-address-manager/pull/77 into release-0.0 branch with slight more changes that removes unrelated capm3 mentions in hack/*.sh files

🌱Use golang as base image and fix capm3 mentions

---

tilt-provider.json

Update tilt-provider.json to add IPAM label in Tilt UX. This [grouping feature](https://blog.tilt.dev/2021/08/09/resource-grouping.html) is supported in tilt version >= v0.22.2.
This patch provides two different grouping strategies:
- by controllers
- and local binaries
Also, the corresponding controller and binary will be grouped under 'IPAM' group label as shown in the local Tilt setup using BMO,CAPM3&IPAM controllers.
Related patches in: [CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/pull/385)&[BMO](https://github.com/metal3-io/baremetal-operator/pull/1061).

✨Use grouping feature of Tilt to add IPAM label

---

OWNERS

Since Jan left the project, currently we have no one on the reviewers' list in the repository. For that reason, this PR removes Jan (@jan-est) from the reviewers' list and proposes to add Michael (@macaptain) to the list as agreed offline.

📖 Add Michael Captain as a reviewer

---

config/rbac/leader_election_role.yaml
main.go

Controller runtime sets by default leader-election-resource-lock to ConfigMapsLeasesResourceLock since v0.7 so consumers can do smooth transitions: https://github.com/kubernetes-sigs/controller-runtime/blob/1730628f118be1128787012c164379e6ac46c75f/pkg/manager/manager.go#L143-L156
Configmap updates to keep the lease alive result in large memory hits for any component that caches/syncs configmaps, particularly the apiserver. Furthermore, it requires additional rbac for controllers. This PR defaults our controller to leases and
should mitigate overwhelming the apiserver in a large management cluster and avoid additional rbac.
Please refer to kubernetes-sigs/cluster-api#5388 and https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/devel …

⚠️ Default LeaderElectionResourceLock to leases

---

README.md

Airship name from CI jenkins view have been deprecated.

✨ Update CI badges with Metal3

---

go.mod
go.sum

github.com/docker/distribution suffers <2.8.0 suffers from GHSA-qq97-vm5h-rrhg

🐛 Uplift docker/distribution to v2.8.0

---

Makefile
hack/ensure-kubectl.sh
hack/fetch_ext_bins.sh

Parameterizes api folder path in the Makefile targets.
Similar as in https://github.com/metal3-io/cluster-api-provider-metal3/pull/523
Also, updates:
- MINIMUM_KUBECTL_VERSION to v1.19.0 
- k8s_version to 1.23.3
to align with CAPM3.

🌱 Parameterize api folder path in Makefile and update kubectl/k8s versions under hack folder files

---

README.md

Updates compatibility table with CAPI. 
CAPM3 [v1.1.0](https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v1.1.0) is out, IPAM [v1.1.1](https://github.com/metal3-io/ip-address-manager/releases/tag/v1.1.1) is also out which both are compatible with CAPI v1.1.2

📖  Update root README compatibility table

---

OWNERS

OWNERS file has been updated recently, and we need to synchronize release-0.1 branch as well, since whole purpose of the initial commit was to overcome the lack of reviewers issue. 
OWNERS file in main branch ref: https://github.com/metal3-io/ip-address-manager/blob/main/OWNERS

📖 Synchronize OWNERS file wih main branch

---

go.mod
go.sum

Uplift release-0.1 branch to use latest CAPI release https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.4.8 in v1a4 release series

🌱 Uplift CAPI module to v0.4.8 in release-0.1 branch

---

go.mod
go.sum

Keeping the github.com/docker/distribution version in sync with [CAPI](https://github.com/kubernetes-sigs/cluster-api/commit/92e9ad9e578f8a6edc80ff8eac13054dcdec94f0)

🌱 Uplift  github.com/docker/distribution v2.8.1

---

ipam/ippool_manager.go

In https://github.com/metal3-io/ip-address-manager/pull/126 I wrongly moved the defer, so that we only patch when the IPClaim has no deletion timestamp. This was wrong, because we need to patch the deleting IPClaims in order to remove the finalizer!
The reason I moved it before, was that the logs were full of attempts to patch IPClaims that were already deleted, so I thought it was unnecessary to patch them.

🐛 Always patch IPClaim

---

controllers/ippool_controller.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go

- Adds a finalizer to all IPAddresses to prevent accidental deletion of them
- Adds a check before deleting IPClaims (and the associated IPAddresses) to see if it is still in use. If the IPClaim has an owner reference to a Metal3Data, it is considered still in use.
- Some confusing comments and log messages edited.
This PR depends on https://github.com/metal3-io/cluster-api-provider-metal3/pull/685 since CAPM3 does not remove the owner refs otherwise, so we get stuck while deleting IPClaims (waiting on the owner ref to go away.
I'm a bit unsure if this should be considered a "feature" or something else. Put 🌱 "other" for now.

🌱 Protect IPAddresses and IPClaims from accidental deletion

---

ipam/ippool_manager.go
ipam/ippool_manager_test.go

The previous implementation was API breaking, since it required the
user/controller owning the IPClaim to remove the ownerRef before the
IPAddress would be deleted. This commit changes it so that we check for
finalizers instead. More specifically, if there are any other finalizers
than the IPAM one, we consider the IPClaim to be still in use. In this
way we "revert" the API breaking change but still get the same
functionality.

🌱 Use finalizers instead of ownerRefs to check if IPClaim is in use

---

Makefile
hack/unit.sh

We started seeing timeouts for the linter that we run as part of the unit tests. This PR increases the timeout from 1m to 5m.

🌱 Increase linter timeout

---

ipam/ippool_manager.go
ipam/ippool_manager_test.go

Related to: https://github.com/metal3-io/cluster-api-provider-metal3/pull/656

 🐛 Don't consider IPAddresses in use when IPPool is being deleted

---

controllers/ippool_controller_test.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go
ipam/manager_factory_test.go

- Add log when clearing IPClaim from IPPools allocations.
- Disable logs for unit tests

🌱 Improve logging when releasing address

---

README.md

https://github.com/metal3-io/ip-address-manager/releases/tag/v1.2.0 is out and we are using the latest versions of CAPI/CAPM3 (v1.2.x) so updates compatibility table accordingly

📖 Update IPAM compatibility table

---

hack/tools/go.mod
hack/tools/go.sum

`hack/tools` was forgotten in https://github.com/metal3-io/ip-address-manager/pull/157
This uplifts the relevant go modules there as well.

🌱 Fix vulnerabilities also in hack/tools

---

go.mod
go.sum

Uplifts CAPI to the latest patch release, which includes security fixes.

🌱 Uplift CAPI to v1.2.5

---

go.mod
go.sum

Uplifts CAPI to the latest patch release, which includes security fixes.

🌱 Uplift CAPI to v1.2.6

---

Dockerfile

This change moves the base container images into ARGs which can be overridden at build time.
N/A

🌱 build: introduce support for FROM overrides

---

hack/Dockerfile.unit

Instead use prow tests and get rid of building extra container image just for unit tests

🌱 Remove unit test container image building Dockerfile

---

hack/shellcheck.sh

Pin shellcheck to 0.9.0 with digest.
Shellcheck 0.9.0 was released this morning. This way it is in line with other repositories, and pinned by digest.

🌱shellcheck: pin to 0.9.0

---

.github/workflows/kubesec.yml
.github/workflows/release.yaml

Set top-level permissions to read, allowing write only where necessary.
Pin actions by a sha.

🐛 .github: secure github actions

---

Dockerfile

Uplift and pin golang 1.19.4 with digest.

🌱 uplift and pin golang 1.19.4 with digest

---

go.mod
go.sum

https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.2

 🌱 Uplift CAPI to v1.3.2

---

go.mod
go.sum

https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.9

🌱 Uplift CAPI to v1.2.9

---

go.mod
go.sum

https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.2

🌱 Uplift CAPI to v1.3.2 

---

config/manager/manager.yaml

It is always good to not rely on the defaults, but be explicit. Set explicit, secure securityContext for the IPAM controller manager deployment and containers.
CAPI has the same starting from upcoming v1.4.0 and cert-manager etc has them already.
Also, reindent manifest properly.

✨ add explicit securitycontexts to controller

---

hack/gomod.sh

gomod.sh has only checked top-level go.mod/go.sum so far, which means api/ and hack/tools go.mods have not been verified.
The script also did not work locally at all, since /workdir was mounted read-only and "go mod tidy" writes to the directory.
Utilize existing "make modules" target.
Manual backport of #199

🐛 hack: gomod needs to verify all go.mod files

---

hack/gomod.sh

gomod.sh has only checked top-level go.mod/go.sum so far, which means api/ and hack/tools go.mods have not been verified.
The script also did not work locally at all, since /workdir was mounted read-only and "go mod tidy" writes to the directory.
Utilize existing "make modules" target.
Uplift Go from insecure 1.17 to 1.18.
Manual backport of #199

hack: gomod needs to verify all go.mod files

---

SECURITY_CONTACTS

Our user-guide is now properly hosted at https://book.metal3.io/

📖  update user-guide url

---

hack/manifestlint.sh

kubeval is not maintained anymore, and suggest moving to kubeconform. Change manifestlint.sh to use kubeconform.
Pin kubeconform image with a version and a digest.
Manual cherry-pick of #185

🐛 manifestlint: move from kubeval to kubeconform

---

.github/workflows/kubesec.yml
.github/workflows/release.yaml

Workflows use resources that are only available when run in the [metal3-io/ip-address-manager](https://github.com/metal3-io/ip-address-manager) repository, so workflow run would always fail when they run in a forked repository. They are of no value to fork repositories. They are triggered by the schedule event, so they cause regular annoying and confusing workflow failure notifications for every fork owner. Rather checking these workflows only in upstream repo is enough.

🌱 Disable scheduled workflows from running in forks

---

VERSIONING.md
docs/api.md

We have two broken links in IPAM:
- CAPI VERSIONING.md is now part of CONTRIBUTING.md
- metal-dev-env integration tests are not doubling as templates anymore
Broken link checker action is added in https://github.com/metal3-io/ip-address-manager/pull/228

📖 fix broken links in markdown files

---

Dockerfile

Bump golang for controller image to 1.19.9

:seedling: bump golang image from 1.19.6 to 1.19.9

---

Dockerfile

Pin distroless/stiac:nonroot to a sha digest.
Bump golang to 1.19.9.

🌱 bump golang image from 1.19.6 to 1.19.9, pin distroless

---

config/crd/bases/ipam.metal3.io_ipaddresses.yaml
config/crd/bases/ipam.metal3.io_ipclaims.yaml
config/crd/bases/ipam.metal3.io_ippools.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
hack/tools/go.mod
hack/tools/go.sum

Bumps controller-tools to v0.11.4. Related to https://github.com/kubernetes-sigs/cluster-api/issues/8546

🌱 Bump controller-tools to v0.11.4

---

.mdlrc
README.md

Remove obsolete `.mdlrc` that ignored couple rules, which hide only a single issue.

🌱 remove mdlrc and fix the one error it ignored

---

.github/dependabot.yml

github-actions was missing from package-ecosystem in dependabot configuration

🐛 Add missing github-actions to  dependabot.yml

---

.github/dependabot.yml

Dependabot is currently not updating gomodules in api/ and hack/tools dir. This PR updates it.

🌱 Include all gomods in different directories for Dependabot

---

hack/tools/install_kustomize.sh

Fixes:
when `make release-manifests` is executed on anything else than amd64 @ Linux
it is failing on:
```
bash: line 1: hack/tools/bin/kustomize: cannot execute binary file: Exec format error
```
This PR downloads the correct binary of kustomize for user's platform.

Add support for mac (kustomize)

---

main.go
main_test.go

This PR adds TLS configuration flags for IPAM.
This enables flags --tls-min-version and --tls-max-version flags, which can be used to limit TLS versions server accepts. Choices are TLS12 and TLS13, so you can force TLS 1.2 only, TLS 1.3 only, or (default) TLS 1.2 and TLS 1.3 is negotiated between server and client.
This also disables TLS 1.0 and TLS 1.1 as they're insecure and obsolete and not supported by Go TLS library.

:sparkles: Add TLS configuration flags for IPAM

---

main.go
main_test.go

Added tls configuration flags to IPAM
This enables flags --tls-min-version and --tls-max-version flags, which can be used to limit TLS versions server accepts. Choices are TLS12 and TLS13, so you can force TLS 1.2 only, TLS 1.3 only, or (default) TLS 1.2 and TLS 1.3 is negotiated between server and client.
This also disables TLS 1.0 and TLS 1.1 as they're insecure and obsolete and not supported by Go TLS library.
Manual backport of https://github.com/metal3-io/ip-address-manager/pull/248

:sparkles: Added TLS configuration flags for IPAM

---

main.go

Fixed the code quality issues mentioned in [1320](https://github.com/metal3-io/baremetal-operator/issues/1320)

:seedling: Fix code quality issues in TLS configuration code

---

docs/releasing.md
go.mod
go.sum

Bump CAPI to v1.4.5 and update releasing doc to make sure we don't miss CAPI bumps before releasing.

Bump CAPI to v1.4.5

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hack/ensure-golangci-lint.sh

As the title says. Also removing depguard linter since it is not used in CAPI anymore and creates issues.

🌱 Bump golangci-lint to v1.54.2

---

docs/releasing.md
go.mod
go.sum

This PR removes unnecessary replace blocks from go modules and updates release doc to check CAPI bumps while releasing.

🌱 Remove unnecessary replace blocks from go modules and update release document

---

Dockerfile

Bump BUILD_IMAGE to golang:1.20.7

🌱 bump golang build_image to 1.20.7

---

examples/generate.sh
go.mod
go.sum

-  Uplifts CAPI to v1.5.1 
-  Cert-manager to v1.12.3

🌱 Bump CAPI to v1.5.1 and cert-manager to v1.12.3

---

examples/generate.sh
go.mod
go.sum

- Uplifts CAPI to v1.4.6
- Uplifts Cert-manager to v1.12.3

🌱  Bump capi to v1.4.6 and cert-manager to v1.12.3

---

hack/tools/release/notes.go

Improve release notes generation by adding empty section for superseded or reverted PRs, aligning empty line addition between image tag and thanking our contributors to same as BMO and CAPM3.

📖 improve release notes tool

---

.github/dependabot.yml

Updating GH actions weekly is excessive noise, run them monthly.

🌱 run dependabot less often for GH actions

---

hack/ensure-golangci-lint.sh

The digest for Linux/amd64 for ensure-golangci-lint are incorrect, and also the script fails to unbound variable when checking the SHA.
This fixes "make lint", and "make test", which are no longer utilized as CI tests, but only run locally.
Makes the script consider ARCH as well, which is the root cause for these mismatches.
Later on, I will add project-infra test to actually verify these scripts work.

🐛 fix ensure-golangci-lint digest for Linux/amd64

---

.golangci.yaml
hack/gosec.sh

Gosec does not handle submodules well. Ignore them and run them separately so they run against correct dependencies.
Bump gosec to 2.17.0 and remove any excludes.
NOTE: In CI, the gosec image is coming via project-infra, this change is only affecting local runs until another PR changes the gosec image there.

🌱 bump gosec to 2.17.0, and fix gosec for submodules

---

.golangci.yaml

I understood this config wrong way around. With the additional config it ignored the #nosec lines, which means it failed linting where they were ignored. Default is working well for us.

🌱 don't ignore #nosec in golangci-lint config

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hack/ensure-golangci-lint.sh
hack/gosec.sh

Gosec does not handle submodules well. Ignore them and run them separately so they run against correct dependencies.
Bump gosec to 2.17.0, and fix new errors it has discovered.
Manual cherry pick of #323, #324, #325 and #317 that bump golangci-lint workflow dependencies.
After this has been merged, PR in project-infra is needed to deactivate gosec in release-1.5, add "test" for release-1.5, and then gosec.sh needs to be removed in release-1.5 via another PR in this repo.
Release 1.4 and release 1.3 will not be bumped.

🌱 bump gosec and fix errors

---

Dockerfile
examples/generate.sh
go.mod
go.sum
hack/ensure-go.sh

- Bump CAPI to v1.4.7
- Bump Cert-manager to v1.13.0
- Bump GO to 1.20.8

🌱 Bumping CAPI to 1.4.7

---

Dockerfile
Makefile
examples/generate.sh
go.mod
go.sum

- Bump CAPI to v1.5.2
- Bump Cert-manager to v1.13.0
- Bump GO to 1.20.8

🌱 Bumping CAPI to 1.5.2

---

docs/releasing.md
hack/verify-release.sh

Add a script to verify release content, before tagging and just before publishing release.
Adapted from https://github.com/metal3-io/cluster-api-provider-metal3/pull/1238 
```console
+# USAGE:
+#
+# This script aims to verify a release content per docs/releasing.md
+# is all done, all images are built and release in general good to go.
+# It can be executed before making a release tag to verify Go dependencies
+# and vulnerabilities are already fixed.
+#
+# Git setup:
+# This script expects to be executed in the root directory of IPAM
+# repository, with the release commit/tag in question checked out.
+#
+# Command line arguments:
+# arg1: mandatory: version without leading v, eg. 1.5.0
+#
+# Environment variables:
+# GITHUB_TOKEN: mandatory: your bearer token that has access to the …
```

🌱 add hack/verify-release.sh script

---

hack/verify-release.sh

Fix missing "grep -E", and remove unneeded curlys after an grep optimization.
This issue is fixed in #340 and #341 cherry-picks already.

🌱 fix hack/verify-release.sh module list printout

---

hack/verify-release.sh

IPAM has test directory but no test module, drop it from the checks.

🌱 drop test tag from verify-release.sh

---

hack/verify-release.sh

Using GLOBIGNORE makes the code simpler, and allows us to ignore the hack/tools/go.mod for sed as well, not just in grep. This fixes issue that module versions are reported as incorrect, if hack/tools/go.mod is the one with wrong version, yet the output then does now show the hack/tools/go.mod as culprit.

🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh

---

hack/verify-release.sh

Github API does not allow fetching draft release notes by tag, only by release id. Add the required code to fetch that, and also do not bail out if it fails, just skip the tests that require the data.
Fix the osv-scanner exiting the script when it finds vulnerabiltiies as well.

🌱 improve hack/verify-release.sh draft release note handling

---

Dockerfile
Makefile

Bump golang version to 1.20.11 which will fix security vulnerability [CVE-2023-45284](https://osv.dev/vulnerability/GO-2023-2186)

🌱Bump golang to 1.20.11 for release-1.5

---

.gitignore
Dockerfile

Bump golang version to 1.20.11 which will fix security vulnerability [CVE-2023-45284](https://osv.dev/vulnerability/GO-2023-2186)
In addition, to go bump, this PR also adds `go.work` related files and some editor related temp files in gitignore.

🌱 Bump golang to 1.20.11 for release-1.4

---

.github/workflows/build-images-action.yml

This PR fixes error in container image build action: https://github.com/metal3-io/ip-address-manager/actions/runs/6981177953/job/18997925577

🐛 Fix error in build image github action

---

.github/dependabot.yml

Dependabot recently is creating quite a few unnecessary PRs which need to be closed manually, having ok-to-test creates a lot of unneeded tests. Removing the label would allow adding labels selectively by reviewers and save some test bandwidth

🌱 Delete "ok-to-test" label from dependabot PRs 

---

hack/markdownlint.sh

Bump markdownlint to 0.13.0. No extra fixes needed in IPAM, and this should be cherry-picked to release branches to keep project-infra config simpler.
TODO: bump the image in project-infra when all bump PRs are merged.

🌱 bump markdownlint to 0.13.0

---

api/v1alpha1/groupversion_info.go
api/v1alpha1/ipaddress_types.go
api/v1alpha1/ipclaim_types.go
api/v1alpha1/ippool_types.go
api/v1alpha1/v1alpha4_suite_test.go

This is recommend for the CAPI providers as mentioned the v1.5 to v1.6 migration guide: https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6#suggested-changes-for-providers.
The original issue was discussed in https://github.com/kubernetes-sigs/cluster-api/issues/9011. The issue is using controller-runtime based scheme builder causes a lot of unnecessary dependancies added in go modules. Compared to that apimachinery was chosen as a better alternative. 
Relevant CAPM3 PR# https://github.com/metal3-io/cluster-api-provider-metal3/pull/1360

🌱 Use k8s apimachinery scheme builder instead of controller-runtime scheme builder

---

.github/workflows/build-images-action.yml
.github/workflows/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/kubesec.yml
.github/workflows/lint-docs.yaml
.github/workflows/pr-verifier.yaml
.github/workflows/release.yaml

`contents: write` is excessive right for dependabot, as we don't allow dependabot to auto-merge anything. It is enough for it to read contents and create pull request.
Move permissions from top-level to job-level as well.
Cleanup actions formatting to be the same for easier reading and maintenance. Add missing version tags.
These is highlighted by the CLOmonitor/OpenSSF Scorecard. This restores score for token permissions to 10/10.

🌱 reduce github action permissions

---

Dockerfile
Makefile

There are some vulnerabilities that are fixed in 1.20.12. They're not affecting us, but scanners nag, so might as well bump.

🌱 bump golang to 1.20.12

---

.github/workflows/dependabot.yml

Dependabot itself wouldn't need more than pull-requests: write, but we have added on generated code part which does need to write contents on top of the PR, so restoring the permissions.
Symptoms are seen in #414

🌱 fix dependabot workflow permissions

---

.markdownlint-cli2.yaml
VERSIONING.md
hack/markdownlint.sh
test/fuzz/README.md

Switch markdownlint container to markdownline-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass

:book: switch markdownlint container to markdownlint-cli2

---

api/v1alpha1/ippool_webhook.go
api/v1alpha1/ippool_webhook_test.go

The current mechanism of checking if an ip address is within the bound of a given ippool loops through the domain of all ip addresses in the ip pool one by one.  A subnet in ipv6 can easily be a very large cidr that involves millions or billions of addresses. The validation webhook could time out (default 10 seconds) before the check is complete, if the ip address being checked is at the end of the cidr range or even out of the range at all.
Fixes #430

🌱 Improve ipv6 address in bound check performance in ippool webhook

---

.github/workflows/release.yaml
Makefile
hack/tools/release/notes.go

Support beta and RC releases in release note generator. Move some logic from Makefile to the release note generator, and then add nice unfolding summary section to hide details in beta/rc notes.
Fix previous release tag pattern detection in Makefile, and make the release note file named after the tag, same as CAPM3.
Example output visible in CAPM3 PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1567

🌱 add support for beta/rc releases in release notes

---

hack/verify-release.sh

Few improvements from previous minor release cycle:
- change artefact to artifact for more common spelling
- match container image detection from release notes to match the earlier change in the release tooling
- rename some of the titles to be more descriptive
- mutate go.mod files for osv-scanner so it can accurately report vulnerablities in golang stdlib (ie. mutate "go 1.21" directive to "go 1.21.9" with patch version read off from main Dockerfile
- check version of osv-scanner, <1.5.0 give weird warnings now
- make docker pull gcrane and osv-scanner images always, so it uses the newest versions
Same as CAPM3 https://github.com/metal3-io/cluster-api-provider-metal3/pull/1626

🌱 improve hack/verify-release.sh

---

Makefile

We had ARCH hard-coded to amd64. This commit changes it so that we take it from go env instead. That way we should automatically get the proper architechture on different devices.
Fixes #517

🌱 Set ARCH based on go env

---

.github/workflows/osv-scanner-scan.yml
.github/workflows/osv-scanner.yml

This PR adds OSV scanner PR and schedule workflows. Workflow files are adapted from https://github.com/google/osv-scanner

🌱 Add OSV scanner PR and schedule workflows

---

Dockerfile
Makefile

Bump golang to 1.21.11 for:
https://osv.dev/vulnerability/GO-2024-2887
https://osv.dev/vulnerability/GO-2024-2888

🌱 bump golang to 1.21.11

---

Dockerfile
Makefile

https://osv.dev/GO-2024-2824
https://osv.dev/GO-2024-2887
https://osv.dev/GO-2024-2888

🌱 bump golang to 1.22.4

---

.github/dependabot.yml

This PR add the following:
- Adds newly introduced multi-directories feature in dependabot. With this hopefully all the go modules would be bumped in one PR for a dependancy. Also this PR optimizes the dependabot configs a bit by adding a group for k8s.io dependancy bump and allowing patch versions for the ignore rules.
- Also add release branch configurations for dependabot

🌱 Optimize the dependabot configuration and add release branch configurations.

---

.github/workflows/release.yaml
.golangci.yaml
Dockerfile
Makefile
api/go.mod
go.mod
hack/codegen.sh
hack/gomod.sh
hack/tools/go.mod
hack/unit.sh

golang 1.21 is deprecating in August 2024, thus bump it to version 1.22
Fixes #596

🌱 Bump golang to v1.22

---

.github/workflows/release.yaml
.golangci.yaml
Dockerfile
Makefile
controllers/ippool_controller_test.go
hack/codegen.sh
hack/gofmt.sh
hack/gomod.sh
hack/govet.sh
hack/unit.sh

This is done since golang 1.20 is already deprecated and branch 1.6 is still supported
Fixes #597

:seedling: Bump golang to 1.22 in release 1.6

---

.github/workflows/build-images-action.yml

The container build wf should only run for upstream repo

:seedling: Container build wf only run for upstream

---

config/manager/manager.yaml

This ensures we have a useful termination message in the Pod if a manager exits unexpectedly.
Check: kubernetes-sigs/cluster-api#10580

🌱 Set terminationMessagePolicy to FallbackToLogsOnError for manager

---

api/go.mod
api/go.sum
config/crd/patches/webhook_in_ipaddresses.yaml
config/crd/patches/webhook_in_ipclaims.yaml
config/crd/patches/webhook_in_ippools.yaml
go.mod
go.sum

Uplift CAPI to 1.8.0 and Drop caBundle from CRDs to support upcoming Kubernetes 1.31.

🌱 Uplift CAPI to 1.8.0 and Drop caBundle from CRDs

---

hack/tools/install_kustomize.sh

We update kustomize syntax to v5 in this PR https://github.com/metal3-io/ip-address-manager/pull/506, but we still haven't upgraded the binary.

:seedling: Bump kustomize to v5.4.3

---

Dockerfile
Makefile

🌱 bump golang to 1.22.7

---

VERSIONING.md
hack/markdownlint.sh

Also fix the new errors it detected.

:seedling: bump markdownlint-cli2 to v0.12.0

---

VERSIONING.md
hack/markdownlint.sh

With fixes to formatting.
Manual cherry-pick of #699

:seedling: bump markdownlint-cli2 to v0.12.0 

---

.github/dependabot.yml

Dependabot always bumps the CAPI main package and CAPI test package separately, which is waste of PRs and CPU time.

:seedling: make CAPI a pattern in dependabot

---

controllers/ippool_controller.go
ipam/ippool_manager.go

Errors during deferred actions were not reported in the result of the main reconcilers. It may mean that the resource will never
get patched if no other reconcile event is triggered.
Same pattern as https://github.com/metal3-io/cluster-api-provider-metal3/pull/2003
**Alternative implementation**
To avoid the check on delete, it is possible to remove [updateObject](https://github.com/metal3-io/ip-address-manager/blob/176d4d0fc738fc3d46a06f2593b982e96a082964/ipam/ippool_manager.go#L457) in deleteAddress. But then if the patch fails (should be a transient error), the IPPool spec and status have already been modified which can have unintended effects.

:bug: Fix ignored errors while patching resources

---

config/manager/manager.yaml

PR will add the` --tls-min-version` flag value to `VersionTLS13` to use TLS 1.3.

🌱 Enable TLS 1.3 flag in IPAM

---

.github/workflows/osv-scanner-scan.yml

Pointing to the workflow file in OSV scanner repository leads to use a commit sha which doesn't correspond to the osv scanner's release tag sha. Hence it is cumbersome to manually check and update the file's sha everytime a new release is there. This PR uses OSV scanner binary and Reported action workflow from release and the sha pinning also corresponds to the release tag. We also tried to use OSV scanner workflow instead of installing the binary but the workflow build the OSV scanner container and the container doesnt have go binary, hence go call analysis fails. Hence we install and use the binary instead.
Also changing the schedule scan time to 6 hours earlier to make it easier to debug the issue.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

🌱 Use OSV-Scanner release binary and Reporter action workflow instead of pointing to a file

---

Makefile

We have seen failure in golint test failure because of time out. Sometimes it takes more than 5 minutes to finish the job. So increasing the test timeout should fix this failure.

🌱 Increase time for golint test to avoid timeout failure

---

Dockerfile
Makefile

**What this PR does / why we need it**: :seedling: Bump Golang to 1.22.9 release 1.8

🌱 Bump Golang to 1.22.9

---

Dockerfile
Makefile

**What this PR does / why we need it**: Bump Golang to 1.22.9

:seedling: Bump Golang to 1.22.9

---

.github/workflows/osv-scanner-scan.yml

Use OSV scanner config, that sets the used go version manually, instead of osv-scanner detecting it from go.mod, which is not correct way for us. Go version from go.mod is not user-friendly way of bumping Go as it forced everyone downstream to use that Go version or newer, forcing unwanted toolchain bumps.
It also changes the reporter action to not fail if there are vulns, we want to get the vulns into Security tab, and failing a scan should mean the scan action itself had issue.
TODO items for later PRs:
- release branch support (scheduled actions cannot target other branches directly)

:seedling: add osv-scanner config for correcting go version used

---

hack/verify-release.sh

Make use of "make go-version" instead of Dockerfile parsing to do golang version related operations. This alters base image version check and also osv-scanner now has a new functionality to override the detected Go version, which we will use via "make go-version" as well.
This cleans up code quite a bit, and does not rely on excessive hacks for the vulnerability scanning.

:seedling: use make go-version instead of Dockerfile parsing in verify-release.sh

---

.github/workflows/golangci-lint.yml
.golangci.yaml
Dockerfile
Makefile
hack/ensure-golangci-lint.sh
ipam/ippool_manager.go

Bump Go to 1.23.3 and golangci-lint to 1.60.3, which supports Go 1.23.
Update golangci-lint config, remove deprecations there.
Fix new issues found by golangci-lint.
Fixes: #716

:seedling: bump Go to 1.23.3 and golangci-lint to 1.60.3

---

Makefile
hack/tools/release/notes.go

- Fixing release note generation logic for beta, rc and minor releases
- Fix markdownlint issues in release note generation.
- Removing `$(MAKE) release-notes` form `make release`, this is not needed, release notes will be fetched from the merged release notes PR.
Fixes #

🌱 Fixing release note generation

---

go.mod
go.sum

**What this PR does / why we need it**: Bump CAPI from v1.9.0-rc.0 to v1.9.0-rc.1

:seedling: Bump CAPI to v1.9.0-rc.1 and controller-runtime to v0.19.3

---

.github/workflows/golangci-lint.yml
Makefile
hack/tools/release/notes.go

Added the hack/tools/release directory to be linted like the rest of the repo. Attempted to do the hack/tools directory but ran into typecheck errors stating that the imports were not packages. Per golangci-lint's docs, [you can't skip or ignore these errors](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors). Instead of modifying the import, I opted for just scanning the actual code.
Something to note, some of the keys within the [.golangci.yml](https://github.com/metal3-io/ip-address-manager/blob/main/.golangci.yaml) at not valid such as the [issues.skip-dirs](https://github.com/metal3-io/ip-address-manager/blob/main/.golangci.yaml#L94) and issues.skip-files. When playing around with the configuration they were a gotcha that …

:seedling: Lint hack/tools

---

Dockerfile
Makefile

**What this PR does / why we need it**: Bump Golang from v1.23.3 to v1.23.4

:seedling: Bump Golang to v1.23.4

---

.github/workflows/build-images-action.yml

The wf is current failing with: "reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps"
https://github.com/metal3-io/ip-address-manager/actions/runs/12311641660

:seedling: Fix container image build workflow

---

README.md

Update build badges for release-1.9.
This should also get us image tagged release-1.9 to fix CI.

:book: update build badges for release-1.9

---

Makefile
docs/releasing.md
hack/tools/release/notes.go

**What this PR does / why we need it**: Fix the path release binary is created in. Add more logging and documentation to reduce user error when using release-notes action from Makefile.

:bug: Fix release-notes in Makefile

---

.github/workflows/build-images-action.yml
.github/workflows/release.yaml

This adds build-container-image as a job in the release wf. After the release note draft is created, the container image will be created.
Fixes #772

:seedling: Add build container image as a job in release wf

---

Dockerfile
Makefile

**What this PR does / why we need it**: Bump Golang to 1.23.4

:seedling: Bump Golang to 1.23.4

---

releasenotes/v1.8.3.md

**What this PR does / why we need it**: make patch release v1.8.3

:rocket: Release v1.8.3

---

README.md

OpenSSF CII Best Practices badge is expected to be repository specific. Our old badge is organization-wide, and does not quality for points in OpenSSF Scorecard for example.
I've done the CII analysis for IPAM alone, and we have received a passing badge for IPAM now.
IPAM evaluation can be found in [bestpractices.net](https://www.bestpractices.dev/en/projects/9968)

:book: update OpenSSF CII Best Practices badge

---

releasenotes/v1.8.4.md

**What this PR does / why we need it**: Release v1.8.4

:rocket: Release v1.8.4

---

.github/workflows/golangci-lint.yml
.github/workflows/lint-docs.yaml
.github/workflows/pr-gh-workflow-approve.yaml
.github/workflows/pr-verifier.yaml

We have "edited" as leftover workaround from days before we had "PR auto-reapprover" workflow in some jobs. In some jobs it is specifically needed as those workflows check the PR metadata which is covered by the edited. Add "ready_for_review" for consistency as a trigger type as well.
Similar PRs will be pushed across Metal3 repos to make things consistent after [discussion in ironic-image PR.](https://github.com/metal3-io/ironic-image/pull/620#pullrequestreview-2604851729)

:seedling: workflows: sync pull_request trigger types

---

Dockerfile
Makefile
README.md
config/default/kustomization.yaml
config/manager/manager.yaml
config/rbac/role.yaml
controllers/ippool_controller.go
controllers/ippool_controller_test.go
controllers/suite_test.go
docs/api.md
examples/generate.sh
examples/ippool/ippool.yaml
examples/provider-components/manager_tolerations_patch.yaml
ipam/ippool_manager.go
ipam/ippool_manager_test.go
ipam/suite_test.go
main.go
metadata.yaml

This commit makes it possible to:
- Deploy IPAM with clusterctl
- Reconsile CAPI's ipaddressclaims with this managers ippools
I have two PR's, one in metal-dev-env and one in CAPM3 to mach these changes 
- metal3-de-env: https://github.com/metal3-io/metal3-dev-env/pull/1459
- CAPM3: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1993
All three PRs' changes need to be tested together. Check test in the metal-dev-env PR.
**What this PR does / why we need it**: To make this IPAM into a provider for CAPI

⚠️ Make ip-address-manager an IPAM provider for CAPI

---

.github/workflows/golangci-lint.yml
.github/workflows/lint-docs.yaml
.github/workflows/pr-gh-workflow-approve.yaml
.github/workflows/pr-verifier.yaml

Re-adding "edited" trigger to testing workflows to workaround Dependabot workflow issue.
Ref: https://github.com/metal3-io/ironic-standalone-operator/issues/162

:seedling: fix dependabot testing issues by re-adding "edited"

---

api/go.mod
api/go.sum
go.mod
go.sum

Bump x/oauth2 to v0.27.0 to get rid uncalled vulnerabilities.

:seedling: bump x/oauth2 to v0.27.0

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hack/ensure-golangci-lint.sh

This PR also bumps golangci-lint-action to 6.5.2. While doing that it removes some of the old unsupported golangci-lint settings.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

🌱  Bump golangci-lint to v1.64.7

---

.golangci.yaml
api/v1alpha1/utils_test.go
controllers/ippool_controller_test.go
controllers/suite_test.go
hack/tools/release/notes.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go
ipam/manager_factory_test.go
ipam/reconcile_error.go
ipam/reconcile_error_test.go
ipam/suite_test.go
ipam/utils.go
ipam/utils_test.go
main.go
test/fuzz/ippool_controller_fuzzer.go
test/fuzz/ippool_manager_fuzzer.go

- Enabled the following linters in `.golangci.yaml`:
- errname 
- forbidigo
- forcetypeassert
- mnd
- perfsprint
- unparam
Fixes: #961
Fixes: #962 
Fixes: #960
Fixes: #965 
Fixes: #966 
Fixes: #967

🌱 Enable errname, forbidigo, forcetypeassert, mnd, perfsprint and unparam linters

---

examples/ippool/ippool.yaml
ipam/ippool_manager.go
ipam/ippool_manager_test.go

**Requirement**: Allocate a specific to IPAddressClaim or IPClaim when created with special label.
**Solution**: During creation of IPAddressClaim, user can provide a special label i.e. ipAddress: <IP_TO_BE_REQUESTED>. Once IPAddressClaim goes for allocation logic in ip_pool_manager, we can handle the allocation of this IP based on the requestedIP and available IPs.
For a happy path scenario, when allocation is successful, we will create IPAddress with the same IP and update IPPool index with the allocated IP.
For a scenario where user has requested an IP which does not belong to range or not available, we can patch IPAddressClaim CR with the error mentioning the same.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …

✨ Adding feature for allocating requested IP

---

.golangci.yaml
hack/tools/release/notes.go

**What this PR does / why we need it**: Release notes are not being generated in a file when `log` is used. We need to use `fmt` instead but [forbidigo](https://github.com/ashanbrown/forbidigo) complains about using fmt so I added an ignore to the `.golangci.yaml`.

:seedling: Fix notes.go so that it still complies with forbidigo

---

.github/dependabot.yml

Replace release-1.8 config with release-1.10 config. Replace as otherwise it would generate PRs towards 1.8 on merge, which we do not want to handle.

:seedling: add dependabot config for release-1.10

---

.golangci.yaml
Dockerfile
Makefile
hack/codegen.sh
hack/gomod.sh
hack/unit.sh

- gomods are still using v1.23.x
- Dockerfile and prow jobs are bumped to use v1.24.3

🌱 Bump golang to v1.24

---

.golangci.yaml
controllers/ippool_controller.go
ipam/ippool_manager.go
ipam/utils_test.go

Enable variable shadowing check in govet linter. Fix warnings caused by running the linter.
**Which issue(s) this PR fixes**:
Fixes #1030

:seedling: Enable variable shadowing check in govet linter

---

Makefile

This PR adds quotation marks around the image field in the makefile rule `set-manifest-image`. This is needed if the image name contains `[` characters. For example, this can happen if the name contains IPv6 address.
Fixes #

:bug: Fix set-manifest-image rule

---

api/go.mod
api/go.sum

This commit:
- syncs the controller-runtime version between the root go.mod and the /api/go.mod
This PR is needed to prepare the repo for v1.11.0-alpha.0 release.

:seedling:  bump controller-runtime version from 0.20.4 to 0.21.0

---

Dockerfile
Makefile

Bumps golang to v1.24.5. This patch has some bug fixes as well uncalled vulnerability fixes for example GHSA-wprm-fgrx-xj42.

🌱 Bump golang to v1.24.5

---

Dockerfile
Makefile

Manual cherry-pick of #1090 to bump golang to 1.24.6.

:seedling: bump golang to 1.24.6

---

controllers/ippool_controller.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go

- Patch only when IPPool is changed.
- Removed unnecessary m.updateStatusTimestamp() calls
NOTE: In API it says:
`// LastUpdated identifies when this status was last observed.`
This seems wrong, firstly I dont think its idea to update something in ippool every time it is observed and secondly even if we are doing it its not named properly. We should change the this text.
- When pool is created for the first time, `IPPool.Status.LastUpdated` is same as `IPPool.CreationTimestamp`. `IPPool.Status.LastUpdated` will only be updated when there is actual change in the ippool which we are doing here: https://github.com/metal3-io/ip-address-manager/blob/main/ipam/ippool_manager.go#L195
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …

🐛 Fix infinite reconciles and timestamp updates

---

api/go.mod
api/go.sum

Bump github.com/onsi/gomega to v1.38.2
Fixes #

🌱 Bump github.com/onsi/gomega to v1.38.2

---

docs/releasing.md

Alpha release mention was missing in release documentation. Alpha release should follow the same convention as beta release.

📖 Add alpha release in release documentation

---

Dockerfile
Makefile

Fixes an uncalled CVE for  net/http (CVE-2025-47910)

:seedling: Bump golang to v1.24.7

---

ipam/ippool_manager.go

Control how many objects (`IPAddressClaimList`,`IPAddressList`, `IPClaimList`,) should be retrieved per
list call (200). This should in theory reduce the load on the API server's memory consumption, especially when there is a large number of objects with large amount of data on them.
Continuation of https://github.com/metal3-io/cluster-api-provider-metal3/pull/2646.
Fixes #

🌱 manager: paginate requests to 200 at a time

---

Dockerfile
Makefile

Uplift go 1.24.8 to address the security vulnerabilities. These minor releases include PRIVATE security fixes to the standard library, covering the following CVEs: [announcement](https://groups.google.com/g/golang-announce/c/ask65OnfzGU)
CVE-2025-61724
CVE-2025-61725
CVE-2025-58187
CVE-2025-61723
CVE-2025-47912
CVE-2025-58185
CVE-2025-58186
CVE-2025-58188
CVE-2025-58183

🌱Uplift go 1.24.8 to address CVEs
