metal3-io/ip-address-manager

ipam/ippool_manager.go

This fixes a bug when the ip address ends with 0 in ipv6, leading to a
name ending with "--". Those are now trimed

🐛 Trim trailing - in IPAddress object names

---

OWNERS

This PR adds some reviewers. Since this repo is fairly new, we cannot expect 10 commits before nominating reviewers. In addition the low number of reviewers might be problematic in this holiday period. Adding some people from the Ericsson team working on Metal3.

🏃 Add fmuyassarov, jan-est and furkatgofurov7 as reviewers

---

hack/codegen.sh

This PR adds a code generation test in the hack folder, to verify that all generation was done properly

🏃 Add code generation test script

---

ipam/ippool_manager.go
ipam/ippool_manager_test.go

This PR updates IPPool status timestamp only when the IPPool allocations are updated.
Fixes #12

:bug: Update IPPool status timestamp only when allocations are updated

---

ipam/ippool_manager_test.go

warning: if block ends with a return statement, so drop this else and outdent its block (golint)
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
Fixes #

Fix small golint issue

---

README.md
docs/api.md

This PR updates CI badges for master branch of IPAM with v1a5 links and fixes some minor issues in the api documentation accordingly to IPAM objects with all required fields needed to run properly example generation Makefile targets.

📖 Update documentation with latest changes

---

OWNERS

I can't commit to being an approver in this repo, so I am removing myself.

:running: remove dhellmann from owners

---

Makefile

Fix kustomize bin usage in Makefile.

🐛 Fix kustomize bin usage in Makefile

---

Makefile
config/default/manager_image_patch.yaml
examples/generate.sh
examples/ippool/ippool.yaml
hack/hack/kind_with_registry.sh

This PR updates examples generation after v1beta1 uplift

 🐛 Update examples generation after v1beta1 uplift

---

README.md

Airship name from CI jenkins view have been deprecated

✨ Update CI badges with Metal3

---

OWNERS

Russel is no longer focusing on the project.

:seedling: Remove russellb as active approver

---

OWNERS

Michael is not working on the project currently thus others volunteered
to be reviewers as there was nobody who would have had 10 or more
commits and isn't already an approver.

:seedling: Modify reviewers

---

go.mod
go.sum
hack/tools/go.mod

Fixes # Also fixing the modules path in hack/tools/go.mod

🌱 Uplift CAPI modules to 1.1.3

---

.github/workflows/kubesec.yml
template/sarif.tpl

Kubesec is a security risk analysis tool for Kubernetes manifest files and this PR is going to add a github action script to IPAM. All the manifest files is going to be scanned by Kubesec once in a week.
[Github action test in Nordix](https://github.com/Nordix/metal3-ipam/actions/runs/2370206224)
[Test result in Nordix](https://github.com/Nordix/metal3-ipam/security/code-scanning?query=is%3Aopen+branch%3Anew-kubesec-moshiur)

🌱 Add kubesec for IPAM

---

README.md

Update build status badges and links.

🌱 Update build status badges

---

OWNERS

I can no longer commit to contributing to Metal3 as I've moved to another project.

🌱 Move fmuyassarov to emeritus_approvers

---

OWNERS

there were a conflict with cherry-pick https://github.com/metal3-io/ip-address-manager/pull/138. This PR fix the conflict and sync owner files

🌱 Move namnx228 to emeritus reviewers

---

go.mod
go.sum

🌱 uplift capi to v1.2.3

---

hack/markdownlint.sh

Pin down markdownlint image to 0.12.0.

🌱hack: use and pin mdl 0.12.0

---

OWNERS

With this I would have 10 commits in the repo.

🌱 Add Lennart as reviewer

---

hack/codegen.sh
hack/gofmt.sh
hack/gomod.sh
hack/gosec.sh
hack/govet.sh
hack/markdownlint.sh

Use docker.io consistently as image registry, and pin more checks by a version and digest.

🌱 use docker.io consistently, and pin more checks

---

OWNERS

🌱 add tuminoid to reviewers

---

hack/gomod.sh

gomod.sh was fixed in main, cherry-pick it for release-1.1.
Manual cherry-pick of #199 .

🐛 cherry-pick gomod.sh fixes from main

---

hack/codegen.sh
hack/ensure-go.sh
hack/ensure-golangci-lint.sh
hack/ensure-kind.sh
hack/ensure-kubectl.sh
hack/ensure-kustomize.sh
hack/fetch_ext_bins.sh
hack/gofmt.sh
hack/gomod.sh
hack/gosec.sh
hack/govet.sh
hack/kind_with_registry.sh
hack/manifestlint.sh
hack/markdownlint.sh
hack/shellcheck.sh
hack/tools/install_kubebuilder.sh
hack/tools/install_kustomize.sh
hack/unit.sh
hack/verify-boilerplate.sh

Cleanup syntax, formatting, indentation etc for scripts in hack. They should be exact copies in each repo (besides if repo specific configuration/files), not a little bit different everywhere.

🌱 cleanup hack/ scripts

---

README.md

Update README.md's compatibility table and build badges.

🌱 update build badges and compatibility table

---

README.md

Update build badges to point to correct release branch.

🌱 update build badges to point to 1.3

---

README.md

Update compatibility table in README.md with release-1.4.

🌱 update compatibility table in README.md

---

Dockerfile

Pin distroless/static:nonroot to a sha digest.

🌱 pin distroless/static:nonroot to a sha digest

---

.github/dependabot.yml

🌱 Add dependabot configuration

---

go.mod
go.sum
test/fuzz/README.md
test/fuzz/ippool_controller_fuzzer.go
test/fuzz/ippool_manager_fuzzer.go

This PR add fuzzing targets for IPAM repository which will later be used by OSS-Fuzz later on.

:seedling: add fuzzing targets for IPAM

---

.github/dependabot.yml

.github/dependabot.yml had some formatting issues. This PR fixes the formatting.

🌱 Fix dependabot.yml yaml formatting

---

main.go

We found out that TLS 1.0 and TLS 1.1 are enabled despite being insecure. These changes are backported to release-1.3 branch, but without the configuration flags. Min version is set to TLS12 and Max version set to TLS13, with no config to change those.

:bug: Disable TLS 1.0 and TLS 1.1

---

api/go.mod
api/go.sum
go.mod
go.sum

🌱 Bump controller-runtime to v0.15.2

---

README.md

After 1.5 release, add 1.5.x to compatibility table.

:book: update README.md on 1.5 release

---

README.md

Update README.md with 1.5 build badges and update compatibility table.

:book: update README.md

---

docs/releasing.md

Clarify module tagging instructions one more time. Signing is also creating annotated tags. Also add reminder to push the tags too.

📖 clarify tag usage in releasing.md

---

hack/verify-release.sh

Manual cherry-pick of #339 without releasing.md parts.
It is identifying quite of few module issues on 1.4 branch btw. I will fix them separately.

🌱 add hack/verify-release.sh

---

go.mod
go.sum

🌱  Bump CAPI to v1.4.8

---

.github/workflows/pr-verifier.yaml

Adding PR title verifier. This uses https://github.com/kubernetes-sigs/kubebuilder-release-tools and makes sure that the title has an icon added. This will make the release process easier.

🌱 Adding PR title verifier

---

.github/workflows/pr-verifier.yaml

The PR verifier action needs `checks: write` after all.

🌱 fix the PR verifier permissions

---

.gitignore
CONTRIBUTING.md

Updating contributing guide regarding signing off of commits

📖 Commit signing off update.

---

.github/workflows/build-images-action.yml

With this PR creation of git tags with pattern `v**` will trigger container image build

🌱 Add tag triggering for container building wf

---

.github/workflows/build-images-action.yml
.github/workflows/dependabot.yml
.github/workflows/lint-docs.yaml
.github/workflows/pr-verifier.yaml

Too many conditionals were added recently (and earlier), remove the extras.

🌱 remove some conditionals from workflows

---

go.mod
go.sum

🌱 Bump CAPI to v1.6.1

---

.gitignore
go.mod
go.sum

🌱 Bumping CAPI to v1.5.6

---

Dockerfile
Makefile

🌱  Bump golang to v1.21.7

---

Dockerfile
Makefile

🌱  Bump golang to v1.20.14

---

api/go.mod
api/go.sum
go.mod
go.sum
hack/tools/go.mod
hack/tools/go.sum

🌱 Bump CAPI to v1.6.2

---

.github/workflows/build-images-action.yml

This workflow is needed in release branch as well.

🌱 add build images action to release-1.5

---

.github/workflows/build-images-action.yml

Fix build image action for release-1.6 and make it consistent with the main.

🌱 fix build image action for release-1.6

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hack/ensure-golangci-lint.sh

🌱 Bump golangci-lint to v1.56.2

---

.gitignore
Makefile

:seedling: Add make unit-cover like in BMO

---

go.mod
go.sum

:seedling: bump CAPI to v1.5.7

---

Dockerfile
Makefile

🌱 bump golang to 1.21.8

---

Dockerfile
Makefile
api/go.mod
api/go.sum
go.mod
go.sum

🌱 Bump golang.org/x/net to v0.23.0 and golang to v1.21.9

---

go.mod
go.sum

 🌱 Bump CAPI to v1.7.0-rc.1

---

go.mod
go.sum

🌱  Bump CAPI  to v1.7.0

---

go.mod
go.sum

🌱 Bump CAPI to v1.5.8

---

go.mod
go.sum

🌱 Bump CAPI to v1.6.4

---

README.md

Updating build status and compatibility table after releasing 1.7

🌱 Update build badges for release-1.7

---

go.mod
go.sum

🌱 bump CAPI to v1.7.1

---

OWNERS

I can't commit to being an approver in this repo, so I am moving myself to emeritus approvers.

🌱 move furkatgofurov7 to emeritus approvers

---

OWNERS

This PR adds the following folks as approvers
- @Rozzii 
- @Sunnatillo 
- @tuminoid 
And also add @mquhuy as a reviewer. 
Well done folks!

🌱 Extend the approvers and reviewers list

---

go.mod
go.sum

🌱 Bump CAPI to v1.7.2

---

api/go.mod
api/go.sum
hack/tools/go.mod
hack/tools/go.sum

Due https://osv.dev/GHSA-8r3f-844c-mc37

🌱 bump protobuf to v1.33.0

---

go.mod
go.sum

🌱 Bump CAPI v1.6.5

---

go.mod
go.sum

🌱 bump capi to 1.7.3

---

go.mod
go.sum

🌱 Bump CAPI to 1.6.6

---

Dockerfile
Makefile

🌱 bump golang to 1.22.5

---

go.mod
go.sum

🌱 Bump CAPI to v1.7.4

---

go.mod
go.sum

🌱 Bump CAPI to v1.8.0-rc.1

---

go.mod
go.sum

Uplifts CAPI to v1.8.1
Part of: https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

🌱  Bump CAPI to v1.8.1

---

Dockerfile
Makefile

🌱  bump golang to 1.22.6

---

.github/dependabot.yml

Add dependabot config for release-1.8 branch.

🌱 add dependabot config for release-1.8

---

.github/dependabot.yml

Wrong ignore rules were put in place for 1.8 branch, fix it.

🌱 fix dependabot config ignore rules

---

README.md

Update release-1.6 1.7 and 1.8 to compatibility table

:book: Update missing releases in compatibility table

---

README.md

Update build badges for release-1.8

:book: Update build badges for release-1.8

---

go.mod
go.sum

🌱 Bump CAPI to v1.7.6

---

go.mod
go.sum

🌱 Bump CAPI to v1.8.3

---

Dockerfile
Makefile

🌱 bump golang to 1.22.8

---

OWNERS_ALIASES

@peppi-lotta has spend a considerable amount of time on redesigning metal3 IPAM as part of the CAPI IPAM provider. I believe her knowledge on the codebase will be very useful for the review process.

🌱  Add Peppi-Lotta as a reviewer

---

go.mod
go.sum

🌱 Bump CAPI to v1.7.8

---

go.mod
go.sum

🌱  Bump CAPI to v1.8.5

---

Makefile

Fix make release target for new flow.
Fixes #

🌱 Fix make release target

---

Makefile

Fix make release target for new flow.
Fixes #

🌱  Fix make release target

---

releasenotes/v1.7.3.md

🚀 Release v1.7.3

---

.github/workflows/build-images-action.yml

Fixes #772 
This should be merged after https://github.com/metal3-io/project-infra/pull/927

:bug: Make image build on releases

---

go.mod
go.sum

:seedling: Bump capi to v1.8.6

---

go.mod
go.sum

:seedling: Bump capi to v1.7.9

---

go.mod
go.sum

:seedling: Bump CAPI to v1.9.0

---

releasenotes/v1.9.0.md

:rocket:  Release v1.9.0

---

releasenotes/v1.9.1.md

🚀 Release v1.9.1

---

OWNERS_ALIASES

Adil has a lot of contributions in IPAM, adding him to reviewers.

:book: add adilGhaffarDev as reviewer

---

.github/workflows/build-images-action.yml

This backports https://github.com/metal3-io/ip-address-manager/pull/789 to release-1.8 branch

:seedling: backport container build image wf to release-1.8 branch

---

.github/workflows/build-images-action.yml

This backports https://github.com/metal3-io/ip-address-manager/pull/789 to release-1.7 branch

:seedling: Backport container build image wf to release-1.7

---

releasenotes/v1.7.4.md

:rocket: Add v1.7.4 release note

---

releasenotes/v1.9.3.md

**What this PR does / why we need it**: Release v1.9.3

:rocket: Release v1.9.3

---

go.mod
go.sum

**What this PR does / why we need it**: Bump CAPI to 1.8.10

:seedling: Bump CAPI to 1.8.10

---

go.mod
go.sum

**What this PR does / why we need it**: Bump CAPI to 1.9.5

:seedling: Bump CAPI to 1.9.5

---

releasenotes/v1.8.5.md

**What this PR does / why we need it**: Release v1.8.5

:rocket: Release v1.8.5

---

releasenotes/v1.9.4.md

**What this PR does / why we need it**: Release v1.9.4

:rocket: Release v1.9.4

---

Dockerfile
Makefile
internal/webhooks/v1alpha1/doc.go
internal/webhooks/v1alpha1/ipaddress_webhook.go
internal/webhooks/v1alpha1/ipaddress_webhook_test.go
internal/webhooks/v1alpha1/ipclaim_webhook.go
internal/webhooks/v1alpha1/ipclaim_webhook_test.go
internal/webhooks/v1alpha1/ippool_webhook.go
internal/webhooks/v1alpha1/ippool_webhook_test.go
main.go

Decouple webhooks from api.
Fixes #

⚠️ Decouple webhooks from api

---

releasenotes/v1.10.0-beta.0.md

**What this PR does / why we need it**: :rocket: Release v1.10.0-beta.0

:rocket: Release v1.10.0-beta.0

---

.golangci.yaml
controllers/ippool_controller_test.go
ipam/ippool_manager_test.go
ipam/utils_test.go

Enable [ginkgolinter](https://github.com/nunnatsa/ginkgolinter) in golangci-lint to find issues in tests and improve their readability. 
**Which issue(s) this PR fixes**:
Fixes #964

:seedling: Enable ginkgolinter

---

OWNERS
OWNERS_ALIASES

Move mquhuy to emeritus reviewers.
Thank you for all the contributions and reviews!

:seedling: move mquhuy to emeritus reviewers

---

go.mod
go.sum

**What this PR does / why we need it**: Bump CAPI to v1.10.0-rc.0

:seedling: Bump CAPI to v1.10.0-rc.0

---

OWNERS_ALIASES

Both have plenty of commits (more than me) and have been doing great contributions to the project.

📖 Make Adil and Peppi maintainers

---

.golangci.yaml

**What this PR does / why we need it**: Enable dupl linter
Fixes #959

:seedling: Enable dupl linter

---

.github/workflows/release.yaml

Set GITHUB_TOKEN in env in release workflow
Fixes #

🌱 Set GITHUB_TOKEN in env in release workflow

---

README.md

limitation documentation related to #694

📖 Limitation regarding IPClaim

---

.golangci.yaml

**What this PR does / why we need it**: Configured tagliatelle linter to use goCamel for json as [discussed here](https://github.com/metal3-io/cluster-api-provider-metal3/pull/2500).
Fixes #

:seedling: Configure tagliatelle linter

---

releasenotes/v1.10.0.md

**What this PR does / why we need it**:  Release v1.10.0

:rocket: Release v1.10.0

---

metadata.yaml

**What this PR does / why we need it**: Update 1.11 to metadata.yaml. This is needed when testing main

:seedling: Update 1.11 to metadata.yaml

---

README.md

**What this PR does / why we need it**: Update release 1.10 to compatibility table

:book: Update release 1.10 to compatibility table

---

.github/workflows/golangci-lint.yml
.golangci.yaml
hack/ensure-golangci-lint.sh

Bump golangci lint v1.64.7
Fixes #

🌱 Bump golangci lint v1.64.7

---

.github/workflows/osv-scanner-scan.yml
hack/verify-release.sh

- Bumps in the verify-release.sh
- Bumps in the osv-scanner workflow

🌱 Bump osv-scanner to v2.1.0

---

go.mod
go.sum

Bump CAPI to v1.11.0-rc.1
Fixes #

🌱 Bump CAPI to v1.11.0-rc.1

---

controllers/ippool_controller.go
ipam/ippool_manager.go
ipam/ippool_manager_test.go

cherry pick of https://github.com/metal3-io/ip-address-manager/pull/1087
Fixes #

🐛 Fix infinite reconciles and timestamp updates

---

README.md

updates the triggers in README to release-1.11.  Also updates the version compatibility table

📖 update build badges for release-1.11

---

README.md

Adds release-v1.11.0 in compatibility matrix

📖  Update compatibility matrix
